export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLES_BY_DATE = 'FILTER_ARTICLES_BY_DATE'

export const FILTER_ARTICLES_BY_COMMENTS_COUNT =
  'FILTER_ARTICLES_BY_COMMENTS_COUNT'
