export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const UPDATE_FILTER_IDS = 'UPDATE_FILTER_IDS'
export const UPDATE_FILTER_DATE_RANGE = 'UPDATE_FILTER_DATE_RANGE'
