export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLE_BY_IDS = 'FILTER_ARTICLE_BY_IDS'

export const FILTER_ARTICLE_BY_PERIOD = 'FILTER_ARTICLE_BY_PERIOD'
